### ISSUE TITLE
Show strike-through text in grey

### ISSUE THREAD

**Issue by claremacrae** [claremacrae/obsidian-experiments-plugin#6]
![image](https://user-images.githubusercontent.com/4840096/137489335-ad15b8a2-e05a-4bba-9221-85a0c995580a.png)

Possibly relevant CSS bits:

![del style - for hyperlink](https://user-images.githubusercontent.com/4840096/137489437-a5003257-225a-4708-98c2-e3a5ab7e3cb0.png)
![del style - for plain text](https://user-images.githubusercontent.com/4840096/137489447-487ff037-5540-4591-9e0e-35fe1f921284.png)

**Comment by claremacrae** [comment]
And in Dark:

![image](https://user-images.githubusercontent.com/4840096/137495116-a139ffa0-b2bb-47b8-988c-6fbaaf321bb3.png)

**Comment by claremacrae** [comment]
I've got something which is good enough:

"dim-strikethrough.css":

```css
/* Strikethrough */
/* This draws hyperlinks in grey - instead of the
   preferable modification of their original shade */
del,
.cm-strikethrough,
del .internal-link,
.external-link del {
    color: var(--text-faint) !important;
    text-decoration-color: var(--text-faint) !important;
    text-decoration-thickness: 1px !important;
}
```
